name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build_release
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        device:
          - akershus
          - beryllium
          - dipper
          - draco
          - enchilada
          - equuleus
          - fajita
          - judyp
          - judypn
          - judyln
          - m1882
          - m1892
          - nx616j
          - olympic
          - pafm00
          - pd1821
          - perseus
          - polaris
          - skr-a0
          - star2qltechn
          - trident

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install requires packages
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext

      - name: Build device ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: To be filled. 待填充
          files: boot-${{ matrix.device }}.img
